
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author w1546167
 */
public class UserLog extends javax.swing.JFrame {

    /**
     * Creates new form UserLog
     */
    public UserLog() {
        initComponents();
        ArrayList<String> TempHolder = new ArrayList<>();
        //Do not allow users to edit log
        UserLogTA.setEditable(false);
        int ShiftLetters = 7;
        
        //My group suggested that i should not include personal details such as username in a user log.
        //I completely disagree with this due to the conventions of a user log. In a typical user log, 
        //A brief description of who the user is and what they have done at what time is the usual convention.
        //Therefore i have left it in.
        //However, i did not gain nothing from their feedback, it made me realise that some information is personal and i should
        //be really careful as to what to display in a userlog just incase it breaks the rules of keeping some information private.
        
        
        
        

        //Reads in every single line of the text file and places it in the Userlogtextarea
        String line;
        try{
            BufferedReader in = new BufferedReader(new FileReader("H:\\SECOND YEAR COMPUTER SCIENCE\\Term2\\Software\\Software CW\\Software edit files\\Tutorialv1.4\\UserLog.txt"));
            line = in.readLine();
            while (line != null){
                //adds each line in an array and then uses my decrypt method to decrypt it
                TempHolder.add(Registration.Decrypt(line, ShiftLetters)); 
                line = in.readLine();
            }
            in.close();
            
            //For statement which gets the size of the array and prints out a new line in the user log.
            for (int i = 0; i < TempHolder.size(); i++){
                UserLogTA.append(TempHolder.get(i) + "\r\n");
            }
            //UserLogTA.read(in, null);
            //UserLogTA.requestFocus();


            
            
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(rootPane, "Could not locate text file");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        UserLogTA = new javax.swing.JTextArea();
        GoBackButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UserLog");

        UserLogTA.setColumns(20);
        UserLogTA.setRows(5);
        jScrollPane1.setViewportView(UserLogTA);

        GoBackButton.setText("Go back");
        GoBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("All user's Log history");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(GoBackButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GoBackButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GoBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackButtonActionPerformed
        //dispose this form
        this.dispose();
        //creates link from log to search
        Search LinkUserLogToSearch = new Search();
        //Sets search to visible
        LinkUserLogToSearch.setVisible(true);
    }//GEN-LAST:event_GoBackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoBackButton;
    private javax.swing.JTextArea UserLogTA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
